apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaffolder-demo
  description: scaffolder-demo
  annotations:
    github.com/project-slug: angeelsanchez/scaffolder-demo
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: scaffolder-demo
    argocd/app-namespace: argocd
    backstage.io/kubernetes-id: scaffolder-demo
    backstage.io/kubernetes-namespace: demo-apps
    backstage.io/kubernetes-label-selector: app=scaffolder-demo
    quay.io/repository-slug: redhat-community-of-practice/backstage-ptc
  tags:
    - nodejs
    - kubernetes
spec:
  type: service
  lifecycle: experimental
  owner: guests
